routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BackEndController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatientsController;
use App\Http\Controllers\PatientVacinateController;
use App\Http\Controllers\PaysController;
use App\Http\Controllers\ProvinceController;
use App\Http\Controllers\RegionsController;
use App\Http\Controllers\VacineCalendarController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/verify-status', function () {
    return view('verify-status');
})->name('verify_status');

Route::get('/offline', function(){
    return view('offlines.offline');
});
Route::get('/list_vacinate', [PagesController::class, 'offlineSubmission'])->middleware('auth')->name('offline_submission');
Route::get('/list_patient', [PagesController::class, 'offlineAddPatient'])->middleware('auth')->name('offline_add_patient');
Route::get('/offline_vacinate', [PagesController::class, 'offlineForm'])->middleware('auth')->name('offline_form');
Route::get('/offline_show', [PagesController::class, 'offlineShow'])->middleware('auth')->name('offline_show_patient');
Route::get('/list_patient', [PagesController::class, 'offlineAddPatient'])->middleware('auth')->name('offline_add_patient');

Route::middleware(['auth:sanctum', 'verified'])->group(function(){
    Route::get('/home', [PagesController::class, 'index'])->name('home');
    Route::get('/profile', [PagesController::class, 'profile'])->name('profile');
});

Route::middleware(['auth:sanctum', 'verified', 'authadmin'])->group(function(){
    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');
    Route::get('/list_user', [AdminController::class, 'listUser'])->name('list_user');
    Route::get('/seting', [AdminController::class, 'setings'])->name('setings');
    Route::resource('update_user', UserController::class);
    Route::post('/redirect', [AdminController::class, 'redirectNotify'])->name('notify');
    Route::get('/new_campagne', [AdminController::class, 'notifyCampagne'])->name('new_campagne');
    Route::get('/notification_rappel', [AdminController::class, 'notifyRappel'])->name('notification_rappel');
});


Route::resource('patient', PatientsController::class)->middleware(['auth']);
Route::resource('vaccinate', PatientVacinateController::class)->middleware('auth');
Route::resource('calendar', VacineCalendarController::class)->middleware(['auth']);
Route::resource('regions', RegionsController::class)->middleware(['authadmin']);
Route::resource('provinces', ProvinceController::class)->middleware(['auth']);
Route::resource('pays', PaysController::class)->middleware(['authadmin']);

Route::get('/add_vacinate/{id}', [PatientVacinateController::class, 'addVacinate'])->middleware('auth')->name('add_vacination');
Route::post('/set_user_status/{id}/{status}', [UserController::class, 'setStatus'])->middleware('auth')->name('set_user_status');
Route::get('/get_province/{id}', [BackEndController::class, 'getProvince'])->middleware('auth')->name('get_province');

// Setting for patients
Route::get('/search', [BackEndController::class, 'showForm'])->name('search');
Route::post('/response', [BackEndController::class, 'getResponse'])->name('response');

resources/views/layouts/partials/choose_province.blade.php
@php
    $list_regions = App\Models\Regions::all();
@endphp

<div class="form-group">
    <label class="control-label" for="region_id"> {{ __('Choisir une région') }} </label>
    <select name="region_id" required id="region_id" class="form-control mb-3 custom-select" onchange="get_region_id(this.value)">
        <option value=""> Choisir une région </option>
        @foreach($list_regions as $region)
            <option value="{{ $region['id'] }}" {{ old('region_id') == $region['id'] ? "selected" : "" }}> {{ $region['title'] }} </option>
        @endforeach
    </select>
    {!! $errors->first('region_id', '<span class="text-danger">:message</span>') !!}

    <div class="invalid-feedback">
        Veuillez choisir une région
    </div>
</div>

<div class="form-group">
    <label class="control-label" for="province_id"> {{ __('Choisir une province') }} </label>
    <select name="province_id" id="province_id" class="form-control mb-3 custom-select">
        <option value=""> Choisir une province </option>
    </select>
    {!! $errors->first('province_id', '<span class="text-danger">:message</span>') !!}
    <div class="invalid-feedback">
        Veuillez choisir une province
    </div>
</div>

resources/views/layouts/partials/flash_msg.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('error'))
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('warning'))
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('info'))
    <div class="alert alert-info alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($errors->any())
    <div class="alert alert-danger">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        Check the following errors :(
    </div>
@endif

resources/views/layouts/partials/footer.blade.php
<div class="container-fluid bg_color text-white">
    <div class="row">
        <div class="text-center mt-2">
            <span class="col-md-3 logo_space">
                <img src="{{ asset('images/eSante-05.jpg') }}" alt="logo" class="img_size">
            </span>

            <span class="col-md-3 logo_space">
                <img src="{{ asset('images/drapeau_bf.png') }}" alt="drapeau_bf" class="img_size">
            </span>

            <span class="col-md-3 logo_space">
                <img src="{{ asset('images/logo_cloudlyYours.jpg') }}" alt="logo_cloudlyYours" class="img_size">
            </span>

            <span class="col-md-3 logo_space">
                <img src="{{ asset('images/logo-africasys150.png') }}" alt="logo-africasys" class="img_size">
            </span>

            <span class="col-md-3">
                <img src="{{ asset('images/logo.png') }}" alt="logo_davycas" class="img_size">
            </span>
        </div>
    </div>

    <div class="text-center mt-2">
        © Copyright {{ Date('Y') }} - All Rights Reserved
    </div>
</div>

resources/views/layouts/partials/menu_top.blade.php
<nav class="navbar navbar-expand-lg navbar-light fixed-top bg_color" style="padding-top: 0px; padding-bottom: 0px">
	<a class="navbar-brand text-white" href="/">
		<img src="{{ asset('images/icon-72x72.png') }}" class="logo_menu" alt="logo">
	</a>

	<button class="navbar navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav me-auto mb-2 mb-lg-0">
			@auth
				@if(in_array(Auth::user()->user_role, ['root', 'admin']))
					<li class="nav-item">
						<a class="nav-link text-white" aria-current="page" href="{{ route('dashboard') }}"> {{ __('Dashboard') }} </a>
					</li>
				@else
					<li class="nav-item">
						<a class="nav-link text-white" aria-current="page" href="{{ route('profile') }}"> {{ __('Mon compte') }} </a>
					</li>
				@endif

				<li class="nav-item">
					<a class="nav-link text-white" href="{{ route('home') }}"> {{ __("Accueil") }} </a>
				</li>

				@if(Auth::user()->user_role !== 'guest')
					<li class="nav-item">
						<a class="nav-link text-white" href="{{ route('vaccinate.create') }}"> {{ __("Ajouter une vaccination") }} </a>
					</li>
				@endif

				@if(in_array(Auth::user()->user_role, ['root', 'admin', 'supervisor']))
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							Patients
						</a>

						<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
							<li><a class="dropdown-item" href="{{ route('patient.index') }}"> {{ __('Liste des patients') }} </a></li>
							<li><a class="dropdown-item" href="{{ route('patient.create') }}"> {{ __('Ajouter un patient') }} </a></li>
						</ul>
					</li>

					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle text-white" href="#" id="Dropdown_vaccin" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							Vaccins
						</a>

						<ul class="dropdown-menu" aria-labelledby="Dropdown_vaccin">
							<li><a class="dropdown-item" href="{{ route('calendar.index') }}"> {{ __('Afficher le calendrier')}} </a></li>
							<li><a class="dropdown-item" href="{{ route('calendar.create') }}">{{ __('Ajouter') }}</a> </li>
						</ul>
					</li>
				@endif
				@if(in_array(Auth::user()->user_role, ['root', 'admin', 'collector']))
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ __("Mon activité") }}
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{{ route('offline_submission') }}"> {{ __('Liste des vaccinations') }} </a></li>
                            <li><a class="dropdown-item" href="{{ route('offline_add_patient') }}"> {{ __('Liste des patients') }} </a></li>
                        </ul>
                    </li>
				@endif
			@endauth
		</ul>

		<div class="d-flex">
			<ul class="navbar-nav">
				@auth
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle text-white" data-user="{{ base64_encode(Auth::user()->id) }}" href="#" id="Dropdown_user" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							{{ Auth::user()->name }}
						</a>

						<ul class="dropdown-menu bg_color" aria-labelledby="Dropdown_user">
							<li>
								<a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
									{{ __('Déconnexion') }}
								</a>

								<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
									@csrf
								</form>
							</li>
						</ul>
					</li>
				@else
					<li class="nav-item">
						<a class="nav-link active text-white" aria-current="page" href="{{ route('login') }}"> {{ __("S'authentifier") }} </a>
					</li>

					<li class="nav-item">
						<a class="nav-link active text-white" aria-current="page" href="{{ route('register') }}"> {{ __("S'inscrire") }} </a>
					</li>

					<li class="nav-item">
						<a class="nav-link active text-white" aria-current="page" href="{{ route('search') }}"> {{ __("Patient ?") }} </a>
					</li>
				@endauth
			</ul>
		</div>
	</div>
</nav>

resources/views/layouts/partials/meta.blade.php
<!-- Web Application Manifest -->
<link rel="manifest" href="/manifest.json">

<link rel="shortcut icon" href="/images/icon-72x72.png" type="image/x-icon">
<link rel="manifest" href="/manifest.json">
<meta name="theme-color" content="#00FA9A">

<meta name="description" content="Application de vaccination en ligne">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="application-name" content="e-Santé">
<meta name="apple-mobile-web-app-title" content="e-Santé">
<meta name="theme-color" content="#00FA9A">
<meta name="msapplication-navbutton-color" content="#00FA9A">
<meta name="apple-mobile-web-app-status-bar-style" content="#00FA9A">
<meta name="msapplication-starturl" content="/">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- IOS Support -->
<link rel="icon" sizes="128x128" href="/images/icon-128x128.png">
<link rel="apple-touch-icon" sizes="128x128" href="/images/icon-128x128.png">
<link rel="icon" sizes="192x192" href="icon-192x192.png">
<link rel="apple-touch-icon" sizes="192x192" href="/images/icon-192x192.png">
<link rel="icon" sizes="256x256" href="/images/icon-256x256.png">
<link rel="apple-touch-icon" sizes="256x256" href="/images/icon-256x256.png">
<link rel="icon" sizes="384x384" href="/images/icon-384x384.png">
<link rel="apple-touch-icon" sizes="384x384" href="/images/icon-384x384.png">
<link rel="icon" sizes="512x512" href="/images/icon-512x512.png">
<link rel="apple-touch-icon" sizes="512x512" href="/images/icon-512x512.png">