routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BackEndController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatientsController;
use App\Http\Controllers\PatientVacinateController;
use App\Http\Controllers\PaysController;
use App\Http\Controllers\ProvinceController;
use App\Http\Controllers\RegionsController;
use App\Http\Controllers\VacineCalendarController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/verify-status', function () {
    return view('verify-status');
})->name('verify_status');

Route::get('/offline', function(){
    return view('offlines.offline');
});
Route::get('/list_vacinate', [PagesController::class, 'offlineSubmission'])->middleware('auth')->name('offline_submission');
Route::get('/list_patient', [PagesController::class, 'offlineAddPatient'])->middleware('auth')->name('offline_add_patient');
Route::get('/offline_vacinate', [PagesController::class, 'offlineForm'])->middleware('auth')->name('offline_form');
Route::get('/offline_show', [PagesController::class, 'offlineShow'])->middleware('auth')->name('offline_show_patient');
Route::get('/list_patient', [PagesController::class, 'offlineAddPatient'])->middleware('auth')->name('offline_add_patient');

Route::middleware(['auth:sanctum', 'verified'])->group(function(){
    Route::get('/home', [PagesController::class, 'index'])->name('home');
    Route::get('/profile', [PagesController::class, 'profile'])->name('profile');
});

Route::middleware(['auth:sanctum', 'verified', 'authadmin'])->group(function(){
    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');
    Route::get('/list_user', [AdminController::class, 'listUser'])->name('list_user');
    Route::get('/seting', [AdminController::class, 'setings'])->name('setings');
    Route::resource('update_user', UserController::class);
    Route::post('/redirect', [AdminController::class, 'redirectNotify'])->name('notify');
    Route::get('/new_campagne', [AdminController::class, 'notifyCampagne'])->name('new_campagne');
    Route::get('/notification_rappel', [AdminController::class, 'notifyRappel'])->name('notification_rappel');
});


Route::resource('patient', PatientsController::class)->middleware(['auth']);
Route::resource('vaccinate', PatientVacinateController::class)->middleware('auth');
Route::resource('calendar', VacineCalendarController::class)->middleware(['auth']);
Route::resource('regions', RegionsController::class)->middleware(['authadmin']);
Route::resource('provinces', ProvinceController::class)->middleware(['auth']);
Route::resource('pays', PaysController::class)->middleware(['authadmin']);

Route::get('/add_vacinate/{id}', [PatientVacinateController::class, 'addVacinate'])->middleware('auth')->name('add_vacination');
Route::post('/set_user_status/{id}/{status}', [UserController::class, 'setStatus'])->middleware('auth')->name('set_user_status');
Route::get('/get_province/{id}', [BackEndController::class, 'getProvince'])->middleware('auth')->name('get_province');

// Setting for patients
Route::get('/search', [BackEndController::class, 'showForm'])->name('search');
Route::post('/response', [BackEndController::class, 'getResponse'])->name('response');

app/Models/Patients.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Patients extends Model
{
    use HasFactory;

    protected $fillable = ['full_name', 'province_id', 'birthday', 'name_father', 'name_mother', 'name_mentor', 'name_mentor', 'helper_contact', 'helper_email', 'user_id', 'code_patient', 'genre', 'born_location'];
}

app/Http/Controllers/PatientsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Patient_vaccinate;
use App\Models\Patients;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PatientsController extends Controller
{
    protected function userGuard(){
        if(in_array(Auth::user()->user_role, ['guest'])){
            return redirect()->route('home');
        }
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        $this->userGuard();
        if(Auth::user()->user_role === 'collector'){
            return redirect(route('home'));
        }
        return view('pages.list_patient');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->userGuard();
        return view('patients.add_patient');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->userGuard();

        $this->validate($request, [
            'province_id'   => 'required',
            'name'          => 'required|min:5',
            'birthday'      => 'required',
            'genre'         => 'required',
            'born_location' => 'required|min:2',
            'father_name'   => 'required|min:5',
            'mother_name'   => 'required|min:5',
            'mentor_name'   => 'required|min:5',
            'helper_contact'=> 'required|regex:/^\+/'
        ]);

        Patients::create([
            'province_id'   => $request->province_id,
            'full_name'     => $request->name,
            'birthday'      => $request->birthday,
            'genre'         => $request->genre,
            'born_location' => $request->born_location,
            'name_father'   => $request->father_name,
            'name_mother'   => $request->mother_name,
            'name_mentor'   => $request->mentor_name,
            'helper_contact'=> $request->helper_contact,
            'helper_email'  => $request->helper_email !== null ? $request->helper_email : 'NP',
            'code_patient'  => Str::random(10),
            'user_id'       => Auth::user()->id
        ]);

        if(Auth::user()->user_role === 'collector'){
            return redirect(route('home'));
        }
        return redirect(route('patient.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Patients  $patients
     * @return \Illuminate\Http\Response
     */
    public function show($patients)
    {
        $this->userGuard();

        $info = Patients::findOrFail($patients);
        $vaccination = Patient_vaccinate::where('patient_id', '=', $patients)->get();

        $vaccine_update = DB::select('SELECT * FROM vaccine_calendars WHERE id NOT IN (SELECT vaccine_calendar_id FROM patient_vaccinates WHERE patient_id = '.$patients.')');

        return view('patients.show_patient', ['infos' => $info, 'vaccinations' => $vaccination, 'vaccine_updates' => $vaccine_update]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Patients  $patients
     * @return \Illuminate\Http\Response
     */
    public function edit($patients)
    {
        $this->userGuard();

        $patient = Patients::findOrFail($patients);
        return view('patients.edit_patient', ['patient' => $patient]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Patients  $patients
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $patients)
    {
        $this->userGuard();

        $this->validate($request, [
            'name'          => 'required|min:5',
            'birthday'      => 'required',
            'born_location' => 'required|min:2',
            'father_name'   => 'required|min:5',
            'mother_name'   => 'required|min:5',
            'mentor_name'   => 'required|min:5',
            'helper_contact'=> 'required'
        ]);

        $patient = Patients::findOrFail($patients);
        $patient->update([
            'full_name'     => $request->name,
            'birthday'      => $request->birthday,
            'genre'         => $request->genre,
            'born_location' => $request->born_location,
            'name_father'   => $request->father_name,
            'name_mother'   => $request->mother_name,
            'name_mentor'   => $request->mentor_name,
            'helper_contact'=> $request->helper_contact,
            'helper_email'  => $request->helper_email !== null ? $request->helper_email : 'NP',
            'user_id'       => Auth::user()->id
        ]);

        if(Auth::user()->user_role === 'collector'){
            return redirect(route('home'));
        }
        return redirect()->route('patient.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Patients  $patients
     * @return \Illuminate\Http\Response
     */
    public function destroy(Patients $patients)
    {
        //
    }

    function getUserByinfo($per_page = 15, $code_patient = null, $birthday = null, $born_location = null, $father = null, $mother = null, $helper_contact = null){
        // if($code_patient !== null){
        //     $liste = Patients::where('full_name', 'like', '%'.$code_patient.'%')->OrWhere('code_patient', 'like', '%'.$code_patient.'%')->paginate($per_page);
        // }else if($birthday !== null){
        //     $liste = $this->getInfoPatient('birthday', $birthday, $per_page);
        // }else if($born_location !== null){
        //     $liste = $this->getInfoPatient('born_location', $born_location, $per_page);
        // }else if($father !== null){
        //     $liste = $this->getInfoPatient('name_father', $father, $per_page);
        // }else if($mother !== null){
        //     $liste = $this->getInfoPatient('name_mother', $mother, $per_page);
        // }else if($helper_contact !== null){
        //     $liste = $this->getInfoPatient('helper_contact', $helper_contact, $per_page);
        // }else if($code_patient !== null && $helper_contact !== null){
        //     // $liste = getInfoPatient('')
        // }else{
        //     $liste = Patients::paginate($per_page);
        // }

        // return view('pages.list_patient', ['patients' => $liste]);
    }

    function getInfoPatient($field, $value, $count_item){
        // return Patients::where($field, 'like', '%'.$value.'%')->paginate($count_item);
    }
}

resources/views/patients/add_patient.blade.php
@extends('layouts.app', ['title' => 'Ajouter un patient'])

@section('main_content')
    <div class="row">
        <div class="col-md-6 mt-3 offset-md-3 mb-2">
            <h2 class="text-center"> {{ __('Formulaire patient') }}</h2>

            <form action="{{ route('patient.store') }}" id="form_add_patient" class="needs-validation" novalidate method="post">
                @csrf

                <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                    <label class="control-label" for="name"> {{ __('Nom complet') }} </label>
                    <input type="text" class="form-control" required name="name" id="name" value="{{ old('name') }}" placeholder="Nom complet">
                    {!! $errors->first('name', '<span class="text-danger">:message</span>') !!}
                    <div class="invalid-feedback">
                        Veuillez saisir le nom du patient
                    </div>
                </div>

                <div class="form-group {{ $errors->has('birthday') ? 'has-error' : '' }}">
                    <label class="control-label" for="birthday"> {{ __('Date de naissance') }} </label>
                    <input type="date" class="form-control" name="birthday" value="{{ old('birthday') }}" required id="birthday"/>
                    {!! $errors->first('birthday', '<span class="text-danger">:message</span>') !!}
                    <div class="invalid-feedback">
                        Veuillez choisir la date de naissance
                    </div>
                </div>

                <div class="form-group {{ $errors->has('genre') ? 'has-error' : '' }}">
                    <label class="control-label" for="genre"> {{ __('Genre') }} </label>
                    <select class="form-control custom-select" required name="genre" id="genre">
                        <option value=""> Veuilez choisir le genre </option>
                        <option value="M" {{ old('genre') == 'M' ? "selected" : "" }}> {{ __("Homme") }} </option>
                        <option value="F" {{ old('genre') == 'F' ? "selected" : "" }}> {{ __("Femme") }} </option>
                    </select>
                    {!! $errors->first('genre', '<span class="text-danger">:message</span>') !!}

                    <div class="invalid-feedback">
                        Veuillez choisir le genre du patient
                    </div>
                </div>

                @include('layouts.partials.choose_province')

                <div class="form-group {{ $errors->has('born_location') ? 'has-error' : '' }}">
                    <label class="control-label" for="born_location"> {{ __('Lieu de naissance') }} </label>
                    <input type="text" class="form-control" name="born_location" id="born_location" required value="{{ old('born_location') }}" placeholder="Lieu de naissance">
                    {!! $errors->first('born_location', '<span class="text-danger">:message</span>') !!}
                    <div class="invalid-feedback">
                        Veuillez choisir une province
                    </div>
                </div>

                <div class="form-group {{ $errors->has('father_name') ? 'has-error' : '' }}">
                    <label class="control-label" for="father_name"> {{ __('Nom du père') }} </label>
                    <input type="text" class="form-control" name="father_name" id="father_name" required value="{{ old('father_name') }}" placeholder="Nom du père">
                    {!! $errors->first('father_name', '<span class="text-danger">:message</span>') !!}
                    <div class="invalid-feedback">
                        Veuillez saisir le nom du père
                    </div>
                </div>

                <div class="form-group {{ $errors->has('mother_name') ? 'has-error' : '' }}">
                    <label class="control-label" for="mother_name"> {{ __('Nom de la mère') }} </label>
                    <input type="text" class="form-control" name="mother_name" required id="mother_name" value="{{ old('mother_name') }}" placeholder="Nom de la mère">
                    {!! $errors->first('mother_name', '<span class="text-danger">:message</span>') !!}
                    <div class="invalid-feedback">
                        Veuillez saisir le nom de mère
                    </div>
                </div>

                <div class="form-group {{ $errors->has('mentor_name') ? 'has-error' : '' }}">
                    <label class="control-label" for="mentor_name"> {{ __('Personne à prévenir en cas de besoin') }} </label>
                    <input type="text" class="form-control" name="mentor_name" required id="mentor_name" value="{{ old('mentor_name') }}" placeholder="Nom du personne à prévenir">
                    {!! $errors->first('mentor_name', '<span class="text-danger">:message</span>') !!}
                    <div class="invalid-feedback">
                        Veuillez saisir le nom du personne à prévenir
                    </div>
                </div>

                <div class="form-group {{ $errors->has('helper_contact') ? 'has-error' : '' }}">
                    <label class="control-label" for="helper_contact"> {{ __('Contact en cas de besoin') }} </label>
                    <input type="text" class="form-control" required name="helper_contact" id="helper_contact" value="{{ old('helper_contact') }}" placeholder="Contact en cas de besoin">
                    {!! $errors->first('helper_contact', '<span class="text-danger">:message</span>') !!}
                    <div class="invalid-feedback">
                        Veuillez saisir le contact
                    </div>
                </div>

                <div class="form-group {{ $errors->has('helper_email') ? 'has-error' : '' }}">
                    <label class="control-label" for="helper_email"> {{ __('E-mail (facultatif)') }} </label>
                    <input type="text" class="form-control" name="helper_email" id="helper_email" value="{{ old('helper_email') }}" placeholder="E-mail (NP par défaut)">
                    {!! $errors->first('helper_email', '<span class="text-danger">:message</span>') !!}
                </div>

                <div class="mt-2 align-center offset-md-4">
                    <button class="btn btn-danger" onclick="javascript:history.back();">
                        {{ __('Annuler') }}
                    </button>

                    <button type="submit" id="submit_add_patient" class="btn btn-primary">
                        {{ __('Ajouter') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script_js')
    <script src="{{ asset('js/form_validate.js') }}"></script>
@endsection

resources/views/patients/show_patient.blade.php
@extends('layouts.app', ['title' => 'Information du patient'])

@section('main_content')
    <div class="row">
        <div class="col-md-4">
            <table class="table table-striped">
                <thead>
                    <tr class="text-center">
                        <th colspan="2"> Info du patient </th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td> {{ __("Code du patient: ") }} </td>
                        <td> {{ $infos->code_patient }} </td>
                    </tr>

                    <tr>
                        <td> {{ __("Nom: ") }} </td>
                        <td> {{ $infos->full_name }} </td>
                    </tr>

                    <tr>
                        <td> {{ __("Date de naissance: ") }} </td>
                        <td> {{ $infos->birthday }} </td>
                    </tr>

                    <tr>
                        <td> {{ __("Nom du père: ") }} </td>
                        <td> {{ $infos->name_father }} </td>
                    </tr>

                    <tr>
                        <td> {{ __("Nom de la mère: ") }} </td>
                        <td> {{ $infos->name_mother }} </td>
                    </tr>

                    <tr>
                        <td> {{ __("Personne à prevenir") }} </td>
                        <td> {{ $infos->full_name }} </td>
                    </tr>

                    <tr>
                        <td> {{ __("Contact: ") }} </td>
                        <td> {{ $infos->helper_contact }} </td>
                    </tr>

                    <tr>
                        <td> {{ __("E-mail: ") }} </td>
                        <td> {{ $infos->helper_email }} </td>
                    </tr>
                    @if(Auth::user()->user_role !== 'guest')
                        <tr>
                            <td> {{ __("Action: ") }} </td>
                            <td>
                                <div class="btn-group" role="group">
                                    @if(Auth::user()->user_role !== 'collector')
                                        <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#info_delete"> {{ __("Supprimer") }} </button>
                                    @endif
                                    <a href="{{ route('patient.edit', $infos) }}" class="btn btn-primary"> {{ __("Modifier") }} </a>
                                </div>
                            </td>
                        </tr>
                    @endif
                </tbody>
            </table>

            @if(Auth::user()->user_role !== 'guest')
                @if(get_vacine_status_per_patient($infos->id, $infos->birthday))
                    <a href="{{ route('add_vacination', $infos->code_patient) }}" id="vacine_patient" data-code="{{ $infos->code_patient }}" class="btn btn-success">
                        Ajouter une vaccination
                    </a>
                @endif
            @endif
        </div>

        <div class="col-md-8">
            <h1 class="text-center"> {{ __("Tableau des vaccinations à jour") }} </h1>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead class="justify-between">
                        <tr>
                            <th> {{ __('Date') }} </th>
                            <th> {{ __('Heure') }} </th>

                            <th> {{ __('Vaccin') }} </th>

                            <th> {{ __('Etat') }} </th>

                            <th> {{ __('Rappel du vaccin') }} </th>

                            <th> {{ __('Capture du flacon') }} </th>

                            <th> {{ __('Validité') }} </th>

                            <th> {{ __('Action') }} </th>
                        </tr>
                    </thead>

                    <tbody>
                        @forelse($vaccinations as $vacine)
                            <tr class="{{ $loop->index % 2 == 0 ? 'bg-info text-white' : '' }}">
                                <td> {{ $vacine->date_vacination }} </td>
                                <td> {{ format_vaccinate_time($vacine->time_vacination) }} </td>

                                <td> {{ get_vaccine_name($vacine->vaccine_calendar_id) }} </td>

                                <td> {{ $vacine->vacine_status ? 'A jour' : 'Pas à jour' }} </td>

                                <td> {{ $vacine->rappelle !== null ? $vacine->rappelle : 'NP' }} </td>

                                <td>
                                    @if($vacine->path_capture !== null)
                                        <a href="{{ asset("flacon_images/$vacine->path_capture") }}">
                                            <img src="{{ asset("flacon_images/$vacine->path_capture") }}" width="100px" />
                                        </a>
                                    @else
                                        {{ 'NP' }}
                                    @endif
                                </td>

                                <td> {!! date('Y-m-d') > $vacine->validity_vacine ? '<i class="fa fa-check"></i>' : '<i class="fa fa-times text-danger"></i>' !!} </td>

                                <td>
                                    <a href="{{ route('vaccinate.show', $vacine->id) }}" class="btn btn-success">
                                        Détail
                                    </a>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="6">
                                    <p class="text-danger text-center"> Aucune ligne trouvée</p>
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

            @if(get_vacine_status_per_patient($infos->id, $infos->birthday))
                <h1 class="text-center"> {{ __("Tableau des vaccinations à venir") }} </h1>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th> {{ __('Age') }} </th>

                                <th> {{ __('Vaccin') }} </th>

                                <th> {{ __('Description') }} </th>

                                <th> {{ __('Validité') }} </th>
                            </tr>
                        </thead>

                        <tbody class="bg-gray-200">
                            @forelse($vaccine_updates as $update)
                                <tr class="{{ $loop->index % 2 == 0 ? 'bg-info text-white' : '' }}">
                                    <td> {{ $update->patient_age }} </td>

                                    <td> {{ $update->name_vaccine }} </td>

                                    <td> {{ $update->illness_against }} </td>

                                    <td> {{ $update->status ? 'Valide' : 'Invalide' }} </td>
                                </tr>
                            @empty
                                <p class="text-danger text-center"> Aucune ligne trouvée</p>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            @endif
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="info_delete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"> {{ __("Confirmer la suppression") }} </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body text-center">
                    {{ __("Etes-vous sûr de vouloir supprimer") }}
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> {{ __("Fermer") }} </button>
                    <a href="#" class="btn btn-danger"> {{ __("Supprimer") }} </a>
                </div>
            </div>
        </div>
    </div>
@endsection