routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BackEndController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatientsController;
use App\Http\Controllers\PatientVacinateController;
use App\Http\Controllers\PaysController;
use App\Http\Controllers\ProvinceController;
use App\Http\Controllers\RegionsController;
use App\Http\Controllers\VacineCalendarController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/verify-status', function () {
    return view('verify-status');
})->name('verify_status');

Route::get('/offline', function(){
    return view('offlines.offline');
});
Route::get('/list_vacinate', [PagesController::class, 'offlineSubmission'])->middleware('auth')->name('offline_submission');
Route::get('/list_patient', [PagesController::class, 'offlineAddPatient'])->middleware('auth')->name('offline_add_patient');
Route::get('/offline_vacinate', [PagesController::class, 'offlineForm'])->middleware('auth')->name('offline_form');
Route::get('/offline_show', [PagesController::class, 'offlineShow'])->middleware('auth')->name('offline_show_patient');
Route::get('/list_patient', [PagesController::class, 'offlineAddPatient'])->middleware('auth')->name('offline_add_patient');

Route::middleware(['auth:sanctum', 'verified'])->group(function(){
    Route::get('/home', [PagesController::class, 'index'])->name('home');
    Route::get('/profile', [PagesController::class, 'profile'])->name('profile');
});

Route::middleware(['auth:sanctum', 'verified', 'authadmin'])->group(function(){
    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');
    Route::get('/list_user', [AdminController::class, 'listUser'])->name('list_user');
    Route::get('/seting', [AdminController::class, 'setings'])->name('setings');
    Route::resource('update_user', UserController::class);
    Route::post('/redirect', [AdminController::class, 'redirectNotify'])->name('notify');
    Route::get('/new_campagne', [AdminController::class, 'notifyCampagne'])->name('new_campagne');
    Route::get('/notification_rappel', [AdminController::class, 'notifyRappel'])->name('notification_rappel');
});


Route::resource('patient', PatientsController::class)->middleware(['auth']);
Route::resource('vaccinate', PatientVacinateController::class)->middleware('auth');
Route::resource('calendar', VacineCalendarController::class)->middleware(['auth']);
Route::resource('regions', RegionsController::class)->middleware(['authadmin']);
Route::resource('provinces', ProvinceController::class)->middleware(['auth']);
Route::resource('pays', PaysController::class)->middleware(['authadmin']);

Route::get('/add_vacinate/{id}', [PatientVacinateController::class, 'addVacinate'])->middleware('auth')->name('add_vacination');
Route::post('/set_user_status/{id}/{status}', [UserController::class, 'setStatus'])->middleware('auth')->name('set_user_status');
Route::get('/get_province/{id}', [BackEndController::class, 'getProvince'])->middleware('auth')->name('get_province');

// Setting for patients
Route::get('/search', [BackEndController::class, 'showForm'])->name('search');
Route::post('/response', [BackEndController::class, 'getResponse'])->name('response');

resources/views/vaccines/detail.blade.php
@extends('layouts.app', ['title' => 'Information du vaccin'])

@section('main_content')
    <div class="row">
        <div class="mt-5 col-md-4">
            <a href="#" onclick="javascript:history.back();" class="btn btn-primary"> Revenir en arrière </a>
        </div>

        <div class="col-md-8 mt-3">
            <div>
                <table class="table table-striped">
                    <thead>
                        <tr class="text-center">
                            <th colspan="2"> Info du vaccination </th>
                        </tr>
                    </thead>

                    <tbody>
                        <tr>
                            <td> {{ __("Code du patient: ") }} </td>
                            <td> {{ $patient_code }} </td>
                        </tr>

                        <tr>
                            <td> {{ __("Numéro du lot du vaccin: ") }} </td>
                            <td> {{ $vaccine_info->lot_number_vacine }} </td>
                        </tr>

                        <tr>
                            <td> {{ __("Date de vaccination: ") }} </td>
                            <td> {{ $vaccine_info->date_vacination }} </td>
                        </tr>

                        <tr>
                            <td> {{ __("Heure de vaccination: ") }} </td>
                            <td> {{ $vaccine_info->time_vacination }} </td>
                        </tr>

                        <tr>
                            <td> {{ __("Validité de la vaccination: ") }} </td>
                            <td> {{ date('Y-m-d') > $vaccine_info->validity_vacine ? 'Valide' : 'Invalide' }} </td>
                        </tr>

                        <tr>
                            <td> {{ __("Rappelle: ") }} </td>
                            <td> {{ $vaccine_info->rappelle }} </td>
                        </tr>

                        @if($vaccine_info->path_capture !== null)
                            <tr>
                                <td> {{ __("Capture du flacon du vaccin: ") }} </td>
                                <td> {{ $vaccine_info->path_capture }} </td>
                            </tr>
                        @endif

                        <tr>
                            <td> {{ __("Nom du vaccinateur") }} </td>
                            <td> {{ $vaccine_info->name_doctor }} </td>
                        </tr>

                        <tr>
                            <td> {{ __("Contact: ") }} </td>
                            <td> {{ $vaccine_info->doctor_contact }} </td>
                        </tr>

                        @if($vaccine_info->others_field !== null)
                            <tr>
                                <td> {{ __("Autre: ") }} </td>
                                <td> {{ $vaccine_info->others_field }} </td>
                            </tr>
                        @endif

                        @if(Auth::user()->user_role !== 'guest')
                            <tr>
                                <td> {{ __("Action ") }} </td>
                                <td>
                                    <div class="btn-group" role="group">
                                        @if(Auth::user()->user_role !== 'collector')
                                            <a href="#" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#info_delete">
                                                {{ __('Supprimer') }}
                                            </a>
                                        @endif

                                        <a href="{{ route('vaccinate.edit', $vaccine_info) }}" class="btn btn-primary">
                                            {{ __('Modifier') }}
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="info_delete" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"> {{ __("Confirmer la suppression") }} </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    {{ __("Etes-vous sûr de vouloir supprimer") }}
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"> {{ __("Fermer") }} </button>
                    <a href="#" class="btn btn-danger"> {{ __("Supprimer") }} </a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/vaccines/edit.blade.php
@extends('layouts.app', ['title' => 'Modifier une vaccination'])

@section('main_content')
    <div class="row">
        <div class="col-md-6 offset-md-3 mb-2">
            <h2 class="text-center"> {{ __('Modifier une vaccination') }}</h2>

            <form action="{{ route('vaccinate.update', $vaccine_info->id) }}" enctype="multipart/form-data" method="POST">
                @csrf
                {{ method_field('PUT') }}

                <div class="form-group {{ $errors->has('patient_code') ? 'has-error' : '' }}">
                    <label class="control-label" for="patient_code"> {{ __('Code du patient') }} </label>
                    <input type="text" class="form-control" readonly="true" name="patient_code" id="patient_code" value="{{ old('patient_code') ?? $patient_code }}" placeholder="Code du patient">
                    {!! $errors->first('patient_code', '<span class="text-danger">:message</span>') !!}
                </div>

                <div class="form-group {{ $errors->has('vaccine_name') ? 'has-error' : '' }}">
                    <label class="control-label" for="vaccine_name"> {{ __('Nom du vaccin') }} </label>
                    <select class="form-control custom-select" name="vaccine_name" id="vaccine_name">
                        <option value=""> Veuilez choisir un vaccin </option>
                        @foreach($vaccines as $vaccine)
                            <option value="{{ $vaccine->id }}" {{ old('vaccine_name') === $vaccine->id || $vaccine_info->vaccine_calendar_id === $vaccine->id ? "selected" : "" }}>
                                {{ $vaccine->name_vaccine }}
                            </option>
                        @endforeach
                    </select>
                    {!! $errors->first('vaccine_name', '<span class="text-danger">:message</span>') !!}
                </div>

                <div class="form-group {{ $errors->has('date_vaccinate') ? 'has-error' : '' }}">
                    <label class="control-label" for="date_vaccinate"> {{ __('Date de vaccination') }} </label>
                    <input type="date" class="form-control" name="date_vaccinate" value="{{ old('date_vaccinate') ?? $vaccine_info->date_vacination }}" id="date_vaccinate"/>
                    {!! $errors->first('date_vaccinate', '<span class="text-danger">:message</span>') !!}
                </div>

                <div class="form-group {{ $errors->has('time_vaccinate') ? 'has-error' : '' }}">
                    <label class="control-label" for="time_vaccinate"> {{ __('Heure de vaccination') }} </label>
                    <input type="time" class="form-control" name="time_vaccinate" value="{{ old('time_vaccinate') ?? $vaccine_info->time_vacination }}" id="time_vaccinate"/>
                    {!! $errors->first('time_vaccinate', '<span class="text-danger">:message</span>') !!}
                </div>

                <div class="form-group {{ $errors->has('doctor_name') ? 'has-error' : '' }}">
                    <label class="control-label" for="doctor_name"> {{ __('Nom du docteur ou l\'agent') }} </label>
                    <input type="text" class="form-control" name="doctor_name" id="doctor_name" value="{{ old('doctor_name') ?? $vaccine_info->name_doctor }}" placeholder="Nom du docteur ou l'agent">
                    {!! $errors->first('doctor_name', '<span class="text-danger">:message</span>') !!}
                </div>

                <div class="form-group {{ $errors->has('doctor_phone') ? 'has-error' : '' }}">
                    <label class="control-label" for="doctor_phone"> {{ __('Contact') }} </label>
                    <input type="text" class="form-control" name="doctor_phone" id="doctor_phone" value="{{ old('doctor_phone') ?? $vaccine_info->doctor_contact }}" placeholder="Contact">
                    {!! $errors->first('doctor_phone', '<span class="text-danger">:message</span>') !!}
                </div>

                <div class="form-group {{ $errors->has('lot_number_vaccine') ? 'has-error' : '' }}">
                    <label class="control-label" for="lot_number_vaccine"> {{ __('Numéro du lot du vaccin') }} </label>
                    <input type="tel" class="form-control" name="lot_number_vaccine" id="lot_number_vaccine" value="{{ old('lot_number_vaccine') ?? $vaccine_info->lot_number_vacine }}" placeholder="Numéro du lot du vaccin">
                    {!! $errors->first('lot_number_vaccine', '<span class="text-danger">:message</span>') !!}
                </div>

                <div class="form-group {{ $errors->has('rappelle') ? 'has-error' : '' }}">
                    <label class="control-label" for="rappelle"> {{ __('Temps de rappelle') }} </label>
                    <input type="text" class="form-control" name="rappelle" id="rappelle" value="{{ old('rappelle') ?? ($vaccine_info->rappelle == null ? '' : $vaccine_info->rappelle) }}" placeholder="Temps de rappelle (NP par défaut)">
                    {!! $errors->first('rappelle', '<span class="text-danger">:message</span>') !!}
                </div>

                <div class="form-group {{ $errors->has('image_path') ? 'has-error' : '' }}">
                    <label class="control-label" for="image_path"> {{ __('Photo du flacon du vaccin') }} </label>
                    <input type="file" class="form-control" name="image_path" id="image_path" value="{{ old('image_path') }}" placeholder="Photo du flacon du vaccin">
                    {!! $errors->first('image_path', '<span class="text-danger">:message</span>') !!}
                </div>

                <div class="mt-2 align-center offset-md-4">
                    <button class="btn btn-danger">
                        {{ __('Annuler') }}
                    </button>

                    <button type="submit" class="btn btn-primary">
                        {{ __('Modifier') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/vaccines/edit_calendar.blade.php
@extends('layouts.app', ['title' => 'Modifier un vaccin'])

@section('main_content')
    <div class="row">
        <div class="col-md-6 mt-3 offset-md-3 mb-2">
            <h2 class="text-center"> {{ __('Modifier la vaccination') }}</h2>
            <form action="{{ route('calendar.update', $vacine) }}" class="needs-validation" novalidate method="post">
                @csrf
                {{ method_field('PUT') }}

                <div class="form-group {{ $errors->has('age') ? 'has-error' : '' }}">
                    <label class="control-label" for="age"> {{ __('Age du patient') }} </label>
                    <input type="text" class="form-control" name="age" id="age" required value="{{ old('age') ?? $vacine->patient_age }}" placeholder="Age du patient">
                    {!! $errors->first('age', '<span class="text-danger">:message</span>') !!}
                    <div class="invalid-feedback">
                        Veuillez saisir l'âge du patient
                    </div>
                </div>

                <div class="form-group {{ $errors->has('name_vacine') ? 'has-error' : '' }}">
                    <label class="control-label" for="name_vacine"> {{ __('Nom du vaccin') }} </label>
                    <input type="text"  class="form-control" name="name_vacine" required value="{{ old('name_vacine') ?? $vacine->name_vaccine }}" placeholder="Nom du vaccin" id="name_vacine"/>
                    {!! $errors->first('name_vacine', '<span class="text-danger">:message</span>') !!}
                    <div class="invalid-feedback">
                        Veuillez saisir le nom du vaccin
                    </div>
                </div>

                <div class="form-group {{ $errors->has('name_vacine') ? 'has-error' : '' }}">
                    <label class="control-label" for="vacine_status"> {{ __('Etat du vaccin') }} </label>
                    <select name="vacine_status" required class="form-control" id="vacine_status">
                        <option value=""> Choisir un état </option>
                        <option value="1" {{ old('vacine_status') == "1" ? 'selected' : '' }}> Valide </option>
                        <option value="0" {{ old('vacine_status') == "0" ? 'selected' : '' }}> Non valide </option>
                    </select>

                    {!! $errors->first('vacine_status', '<span class="text-danger">:message</span>') !!}
                    <div class="invalid-feedback">
                        Veuillez choisir l'état du vaccin
                    </div>
                </div>

                <div class="form-group {{ $errors->has('illness') ? 'has-error' : '' }}">
                    <label class="control-label" for="illness"> {{ __('Maladie luttée') }} </label>
                    <textarea  class="form-control" name="illness" id="illness" required style="resize:none" cols="50" rows="10">{{ old('illness') ?? $vacine->illness_against }}</textarea>
                    {!! $errors->first('illness', '<span class="text-danger">:message</span>') !!}
                    <div class="invalid-feedback">
                        Veuillez saisir le description du vaccin
                    </div>
                </div>

                <div class="mt-2 offset-md-4">
                    <a href="#" onclick="javascript:history.back();" class="btn btn-danger">
                        {{ __('Annuler') }}
                    </a>

                    <button type="submit" class="btn btn-primary">
                        {{ __('Ajouter') }}
                    </button>
                </div>
            </form>
        </div>
    </div>  
@endsection

@section('script_js')
    <script>
        const valide_form = () => {
        
        var forms = document.querySelectorAll('.needs-validation')

        Array.prototype.slice.call(forms)
            .forEach(function (form) {
            form.addEventListener('submit', function (event) {
                if (!form.checkValidity()) {
                event.preventDefault()
                event.stopPropagation()
                }

                form.classList.add('was-validated')
            }, false)
            })
        }
        valide_form();
    </script>
@endsection

resources/views/vaccines/vacinate_patient.blade.php
@extends('layouts.app', ['title' => 'Ajouter une vaccination'])

@section('main_content')
    <div class="row">
        <div class="col-md-6 mt-3 offset-md-3 mb-2">
            <h2 class="text-center"> {{ __('Ajouter une vaccination') }}</h2>

            <form action="{{ route('vaccinate.store') }}" id="form_vacinate" enctype="multipart/form-data" class="needs-validation" novalidate method="post">
                @csrf

                <div class="form-group">
                    <label class="control-label" for="patient_code"> {{ __('Code du patient') }} </label>
                    <input type="text" class="form-control" name="patient_code" required id="patient_code" value="{{ old('patient_code') ?? ($patient_code ?? '') }}" @if(isset($patient_code)){{ 'readonly' }} @endif placeholder="Code du patient">
                    {!! $errors->first('patient_code', '<span class="text-danger">:message</span>') !!}

                    <div class="invalid-feedback">
                        Veuillez saisir le code du patient
                    </div>
                </div>

                <div class="form-group d-none" id="patient_name">
                    <label class="control-label" for="patient_info"> {{ __('Nom complet du patient') }} </label>
                    <input type="text" name="patient_info" class="form-control" id="patient_info" readonly>
                </div>

                <div class="form-group {{ $errors->has('vaccine_name') ? 'has-error' : '' }}">
                    <label class="control-label" for="vaccine_name"> {{ __('Nom du vaccin') }} </label>
                    <select class="form-control custom-select" required name="vaccine_name" id="vaccine_name">
                        <option value=""> Veuilez choisir un vaccin </option>
                        @foreach($vaccines as $vaccine)
                            <option value="{{ $vaccine->id }}" {{ old('vaccine_name') == $vaccine->id ? "selected" : "" }}> {{ $vaccine->name_vaccine }} </option>
                        @endforeach
                    </select>
                    {!! $errors->first('vaccine_name', '<span class="text-danger">:message</span>') !!}

                    <div class="invalid-feedback">
                        Veuillez choisir le nom du vaccin
                    </div>
                </div>

                <div class="form-group {{ $errors->has('date_vaccinate') ? 'has-error' : '' }}">
                    <label class="control-label" for="date_vaccinate"> {{ __('Date de vaccination') }} </label>
                    <input type="date" class="form-control" required name="date_vaccinate" value="{{ old('date_vaccinate') }}" id="date_vaccinate"/>
                    {!! $errors->first('date_vaccinate', '<span class="text-danger">:message</span>') !!}

                    <div class="invalid-feedback">
                        Veuillez choisir une date
                    </div>
                </div>

                <div class="form-group {{ $errors->has('time_vaccinate') ? 'has-error' : '' }}">
                    <label class="control-label" for="time_vaccinate"> {{ __('Heure de vaccination') }} </label>
                    <input type="time" class="form-control" required name="time_vaccinate" value="{{ old('time_vaccinate') }}" id="time_vaccinate"/>
                    {!! $errors->first('time_vaccinate', '<span class="text-danger">:message</span>') !!}

                    <div class="invalid-feedback">
                        Veuillez choisir l'heure
                    </div>
                </div>

                <div class="form-group {{ $errors->has('lot_number_vaccine') ? 'has-error' : '' }}">
                    <label class="control-label" for="lot_number_vaccine"> {{ __('Numéro du lot du vaccin') }} </label>
                    <input type="text" class="form-control" required name="lot_number_vaccine" id="lot_number_vaccine" value="{{ old('lot_number_vaccine') }}" placeholder="Numéro du lot du vaccin">
                    {!! $errors->first('lot_number_vaccine', '<span class="text-danger">:message</span>') !!}

                    <div class="invalid-feedback">
                        Veuillez saisir le numéro du vaccin
                    </div>
                </div>

                <div class="form-group {{ $errors->has('rappelle') ? 'has-error' : '' }}">
                    <label class="control-label" for="rappelle"> {{ __('Temps de rappel') }} </label>
                    <input type="text" class="form-control" name="rappelle" id="rappelle" value="{{ old('rappelle') }}" placeholder="Temps de rappel (NP par défaut)">
                    {!! $errors->first('rappelle', '<span class="text-danger">:message</span>') !!}
                </div>

                <div class="form-group {{ $errors->has('image_path') ? 'has-error' : '' }}">
                    <label class="control-label" for="image_path"> {{ __('Photo du flacon du vaccin') }} </label>
                    <input type="file" class="form-control" capture="environment" accept="image/*" name="image_path" id="image_path" value="{{ old('image_path') }}">
                    {!! $errors->first('image_path', '<span class="text-danger">:message</span>') !!}
                </div>

                <div class="form-group {{ $errors->has('doctor_name') ? 'has-error' : '' }}">
                    <label class="control-label" for="doctor_name"> {{ __('Nom du docteur ou l\'agent') }} </label>
                    <input type="text" class="form-control" required name="doctor_name" id="doctor_name" value="{{ old('doctor_name') }}" placeholder="Nom du docteur ou l'agent">
                    {!! $errors->first('doctor_name', '<span class="text-danger">:message</span>') !!}

                    <div class="invalid-feedback">
                        Veuillez saisir le nom de l'agent
                    </div>
                </div>

                <div class="form-group {{ $errors->has('doctor_phone') ? 'has-error' : '' }}">
                    <label class="control-label" for="doctor_phone"> {{ __('Contact') }} </label>
                    <input type="text" class="form-control" required name="doctor_phone" id="doctor_phone" value="{{ old('doctor_phone') }}" placeholder="Contact">
                    {!! $errors->first('doctor_phone', '<span class="text-danger">:message</span>') !!}

                    <div class="invalid-feedback">
                        Veuillez saisir le contact
                    </div>
                </div>

                <div class="mt-2 align-center offset-md-4">
                    <button class="btn btn-danger"  onclick="javascript:history.back();">
                        {{ __('Annuler') }}
                    </button>

                    <button type="submit" id="submit_vacinate_patient" class="btn btn-primary">
                        {{ __('Ajouter') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script_js')
    <script src="{{ asset('js/form_validate.js') }}"></script>
@endsection

resources/views/vaccines/vacine_calendar.blade.php
@extends('layouts.app', ['title' => 'Ajouter un vaccin'])

@section('main_content')
    <div class="row">
        <div class="col-md-6 mt-3 offset-md-3 mb-2">
            <h2 class="text-center"> {{ __('Ajouter dans le calendrier') }} </h2>

            <form action="{{ route('calendar.store') }}" class="needs-validation" novalidate method="post">
                @csrf

                <div class="form-group {{ $errors->has('age') ? 'has-error' : '' }}">
                    <label class="control-label" for="age"> {{ __('Age du patient') }} </label>
                    <input type="text" class="form-control" name="age" id="age" required value="{{ old('age') }}" placeholder="Age du patient">
                    {!! $errors->first('age', '<span class="text-danger">:message</span>') !!}
                    <div class="invalid-feedback">
                        Veuillez saisir l'age du patient
                    </div>
                </div>

                <div class="form-group {{ $errors->has('name_vacine') ? 'has-error' : '' }}">
                    <label class="control-label" for="name_vacine"> {{ __('Nom du vaccin') }} </label>
                    <input type="text"  class="form-control" name="name_vacine" required value="{{ old('name_vacine') }}" placeholder="Nom du vaccin" id="name_vacine"/>
                    {!! $errors->first('name_vacine', '<span class="text-danger">:message</span>') !!}
                    <div class="invalid-feedback">
                        Veuillez saisir le nom du vaccin
                    </div>
                </div>

                <div class="form-group {{ $errors->has('illness') ? 'has-error' : '' }}">
                    <label class="control-label" for="illness"> {{ __('Maladie luttée') }} </label>
                    <textarea  class="form-control" name="illness" id="illness" style="resize:none" required cols="50" rows="10">{{ old('illness') }}</textarea>
                    {!! $errors->first('illness', '<span class="text-danger">:message</span>') !!}
                    <div class="invalid-feedback">
                        Veuillez saisir une description
                    </div>
                </div>

                <div class="mt-2 align-center offset-md-4">
                    <button class="btn btn-danger" onclick="javascript:history.back();">
                        {{ __('Annuler') }}
                    </button>

                    <button type="submit" class="btn btn-primary">
                        {{ __('Ajouter') }}
                    </button>
                </div>
            </form>
        </div>
    </div>  
@endsection

@section('script_js')
    <script src="{{ asset('js/form_validate.js') }}"></script>
@endsection