routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\BackEndController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\PatientsController;
use App\Http\Controllers\PatientVacinateController;
use App\Http\Controllers\PaysController;
use App\Http\Controllers\ProvinceController;
use App\Http\Controllers\RegionsController;
use App\Http\Controllers\VacineCalendarController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/verify-status', function () {
    return view('verify-status');
})->name('verify_status');

Route::get('/offline', function(){
    return view('offlines.offline');
});
Route::get('/list_vacinate', [PagesController::class, 'offlineSubmission'])->middleware('auth')->name('offline_submission');
Route::get('/list_patient', [PagesController::class, 'offlineAddPatient'])->middleware('auth')->name('offline_add_patient');
Route::get('/offline_vacinate', [PagesController::class, 'offlineForm'])->middleware('auth')->name('offline_form');
Route::get('/offline_show', [PagesController::class, 'offlineShow'])->middleware('auth')->name('offline_show_patient');
Route::get('/list_patient', [PagesController::class, 'offlineAddPatient'])->middleware('auth')->name('offline_add_patient');

Route::middleware(['auth:sanctum', 'verified'])->group(function(){
    Route::get('/home', [PagesController::class, 'index'])->name('home');
    Route::get('/profile', [PagesController::class, 'profile'])->name('profile');
});

Route::middleware(['auth:sanctum', 'verified', 'authadmin'])->group(function(){
    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');
    Route::get('/list_user', [AdminController::class, 'listUser'])->name('list_user');
    Route::get('/seting', [AdminController::class, 'setings'])->name('setings');
    Route::resource('update_user', UserController::class);
    Route::post('/redirect', [AdminController::class, 'redirectNotify'])->name('notify');
    Route::get('/new_campagne', [AdminController::class, 'notifyCampagne'])->name('new_campagne');
    Route::get('/notification_rappel', [AdminController::class, 'notifyRappel'])->name('notification_rappel');
});


Route::resource('patient', PatientsController::class)->middleware(['auth']);
Route::resource('vaccinate', PatientVacinateController::class)->middleware('auth');
Route::resource('calendar', VacineCalendarController::class)->middleware(['auth']);
Route::resource('regions', RegionsController::class)->middleware(['authadmin']);
Route::resource('provinces', ProvinceController::class)->middleware(['auth']);
Route::resource('pays', PaysController::class)->middleware(['authadmin']);

Route::get('/add_vacinate/{id}', [PatientVacinateController::class, 'addVacinate'])->middleware('auth')->name('add_vacination');
Route::post('/set_user_status/{id}/{status}', [UserController::class, 'setStatus'])->middleware('auth')->name('set_user_status');
Route::get('/get_province/{id}', [BackEndController::class, 'getProvince'])->middleware('auth')->name('get_province');

// Setting for patients
Route::get('/search', [BackEndController::class, 'showForm'])->name('search');
Route::post('/response', [BackEndController::class, 'getResponse'])->name('response');

resources/views/pages/calendar.blade.php
@extends('layouts.app', ['title' => 'Calendrier de vaccination'])

@section('main_content')
    <br>
    <div class="row">
        <h1 class="text-center"> Calendrier de vaccination au Burkina Faso </h1>

        {{Auth::user()->user_right}}
        
        <div class="table-responsive-sm">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th> {{ __('Age') }} </th>

                        <th> {{ __('Nom du vaccin') }} </th>
                        
                        <th> {{ __('Prevention contre') }} </th>
                        
                        <th> {{ __('Validité') }} </th>
                        
                        @if(!in_array(Auth::user()->user_role, ['collector', 'guest']))
                            <th> {{ __('Action') }} </th>                            
                        @endif
                    </tr>
                </thead>

                <tbody>
                    @foreach($vacines as $vacine)
                        <tr>
                            <td> {{ $vacine->patient_age }} </td>

                            <td> {{ $vacine->name_vaccine }} </td>
                            
                            <td> {{ $vacine->illness_against }} </td>

                            <td> {{ $vacine->status === '1'? 'En cours' : 'Interdit' }} </td>
                            
                            @if(!in_array(Auth::user()->user_role, ['collector', 'guest']))
                                <td>
                                    <a href="{{ route('calendar.edit', $vacine) }}" class="btn btn_color text-white">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                </td>
                            @endif
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

        <div class="offset-md-5">
            {{ $vacines->links() }}
        </div>
    </div>
@endsection

resources/views/pages/list_patient.blade.php
@extends(in_array(Auth::user()->user_role, ['root']) ? 'layouts.app' : 'layouts.app', ['title' => 'Liste des patients'])

@section('main_content')
    <div>
        @livewire('list-patients')
    </div>
    {{-- <h1 class="text-center"> Liste des patients </h1>
    
    <div class="row mt-4">
        <form action="{{ route('getUserByinfo') }}" method="GET">
            @csrf

            <div class="row">
                <div class="form-floating col-md-2">
                    <input type="text" class="form-control" placeholder="Nom ou code du patient" id="floatingSearch" name="search">
                    <label for="floatingSearch"> {{ __("Nom ou code du patient") }} </label>
                </div>
    
                <div class="form-floating col-md-2">
                    <input type="date" class="form-control" placeholder="Date de naissance" id="floatingBirthday" name="birthday">
                    <label for="floatingBirthday"> {{ __("Date de naissance") }} </label>
                </div>
                
                <div class="form-floating col-md-2">
                    <input type="text" class="form-control" placeholder="Lieu de naissance" id="floatingLocation" name="born_location">
                    <label for="floatingLocation"> {{ __("Lieu de naissance") }} </label>
                </div>
                
                <div class="form-floating col-md-2">
                    <input type="text" class="form-control" placeholder="Nom du père" id="floatingFather" name="name_father">
                    <label for="floatingFather"> {{ __("Nom du père") }} </label>
                </div>
                
                <div class="form-floating col-md-2">
                    <input type="text" class="form-control" placeholder="Nom de la mère" id="floatingMother" name="name_mother">
                    <label for="floatingMother"> {{ __("Nom de la mère") }} </label>
                </div>
                
                <div class="form-floating col-md-2">
                    <input type="text" class="form-control" placeholder="Contact" id="floatingContact" name="helper_contact">
                    <label for="floatingContact"> {{ __("Contact") }} </label>
                </div>
            </div>

            <div class="row mb-2">
                <select class="form-control mt-2 col-md-6 custom-select" name="per_page" id="per_page">
                    @for($i = 5; $i <= 100; $i += 5)
                        <option value="{{ $i }}"> {{ $i }} <option>
                    @endfor
                </select>

                <button class="btn btn-primary mt-2 col-md-4 offset-2">
                    <i class="fa fa-search"></i>
                    {{ __("Rechercher") }}
                </button>
            </div>
        </form>
    </div>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th> {{ __('Code') }} </th>

                    <th> {{ __('Nom') }} </th>

                    <th> {{ __('Date de naissance') }} </th>
                    
                    <th> {{ __('Lieu de naissance') }} </th>
                    
                    <th> {{ __('Nom des parents') }} </th>

                    <th> {{ __('Etat de vaccination') }} </th>

                    <th> {{ __('Action') }} </th>
                </tr>
            </thead>

            <tbody>
                @forelse($patients as $patient)
                    <tr class="{{ $loop->index % 2 == 0 ? 'bg-info text-white' : '' }}">
                        <td> {{ $patient->code_patient }} </td>

                        <td> {{ $patient->full_name }} </td>

                        <td> {{ $patient->birthday }} </td>
                        
                        <td> {{ $patient->born_location }} </td>
                        
                        <td> {{ $patient->name_father.', '.$patient->name_mother }} </td>

                        <td>
                            {!! get_vacine_status_per_patient($patient->id, $patient->birthday) ? '<div class="text-center text-danger"> <i class="fa fa-times fa-2x"></i> </div>' : '<div class="text-center text-success"> <i class="fa fa-check"></i> </div>' !!}
                        </td>
                        
                        <td>
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a href="{{ route('patient.show', $patient) }}" class="btn btn-success">
                                    Afficher
                                </a>

                                @if(get_vacine_status_per_patient($patient->id, $patient->birthday)) 
                                    <a href="{{ route('add_vacination', $patient->code_patient) }}" class="btn btn-warning">
                                        Ajouter vacciner
                                    </a>
                                @endif
                            </div>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7">
                            <center><p class="text-danger"> Aucune ligne trouvée</p></center>
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div> 
    <div class="offset-md-5">
        {{ $patients->links() }}
    </div>
    --}}
    
@endsection

resources/views/pages/profile.blade.php
Hello world

resources/views/pages/response.blade.php
@extends('layouts.app', ['title' => 'Information du patient'])

@section('main_content')
    <div class="row">
        <div class="col-md-4 mt-2">
            <table class="table table-striped">
                <thead>
                    <tr class="text-center">
                        <th colspan="2"> Info du patient </th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td> {{ __("Code du patient: ") }} </td>
                        <td> {{ $infos->code_patient }} </td>
                    </tr>

                    <tr>
                        <td> {{ __("Nom: ") }} </td>
                        <td> {{ $infos->full_name }} </td>
                    </tr>

                    <tr>
                        <td> {{ __("Date de naissance: ") }} </td>
                        <td> {{ $infos->birthday }} </td>
                    </tr>

                    <tr>
                        <td> {{ __("Nom du père: ") }} </td>
                        <td> {{ $infos->name_father }} </td>
                    </tr>

                    <tr>
                        <td> {{ __("Nom de la mère: ") }} </td>
                        <td> {{ $infos->name_mother }} </td>
                    </tr>

                    <tr>
                        <td> {{ __("Personne à prevenir") }} </td>
                        <td> {{ $infos->full_name }} </td>
                    </tr>

                    <tr>
                        <td> {{ __("Contact: ") }} </td>
                        <td> {{ $infos->helper_contact }} </td>
                    </tr>

                    <tr>
                        <td> {{ __("E-mail: ") }} </td>
                        <td> {{ $infos->helper_email }} </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="col-md-8 mt-3">
            <h1 class="text-center"> {{ __("Tableau des vaccinations à jour") }} </h1>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead class="justify-between">
                        <tr>
                            <th> {{ __('Date') }} </th>
                            <th> {{ __('Heure') }} </th>
                            <th> {{ __('Vaccin') }} </th>
                            <th> {{ __('Etat') }} </th>
                            <th> {{ __('Rappel du vaccin') }} </th>
                            <th> {{ __('Capture du flacon') }} </th>
                            <th> {{ __('Validité') }} </th>
                        </tr>
                    </thead>

                    <tbody>
                        @forelse($vaccinations as $vacine)
                            <tr class="{{ $loop->index % 2 == 0 ? 'bg-info text-white' : '' }}">
                                <td> {{ $vacine->date_vacination }} </td>
                                <td> {{ format_vaccinate_time($vacine->time_vacination) }} </td>

                                <td> {{ get_vaccine_name($vacine->vaccine_calendar_id) }} </td>

                                <td> {{ $vacine->vacine_status ? 'A jour' : 'Pas à jour' }} </td>

                                <td> {{ $vacine->rappelle !== null ? $vacine->rappelle : 'NP' }} </td>

                                <td>
                                    @if($vacine->path_capture !== null)
                                        <a href="{{ asset("flacon_images/$vacine->path_capture") }}">
                                            <img src="{{ asset("flacon_images/$vacine->path_capture") }}" width="100px" />
                                        </a>
                                    @else
                                        {{ 'NP' }}
                                    @endif
                                </td>

                                <td>
                                    {!! date('Y-m-d') > $vacine->validity_vacine ? '<i class="fa fa-check"></i>' : '<i class="fa fa-times text-danger"></i>' !!}
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="7">
                                    <p class="text-danger text-center"> Aucune ligne trouvée</p>
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>

            @if(get_vacine_status_per_patient($infos->id, $infos->birthday))
                <h1 class="text-center"> {{ __("Tableau des vaccinations à venir") }} </h1>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th> {{ __('Age') }} </th>

                                <th> {{ __('Vaccin') }} </th>

                                <th> {{ __('Description') }} </th>

                                <th> {{ __('Validité') }} </th>
                            </tr>
                        </thead>

                        <tbody class="bg-gray-200">
                            @forelse($vaccine_updates as $update)
                                <tr class="{{ $loop->index % 2 == 0 ? 'bg-info text-white' : '' }}">
                                    <td> {{ $update->patient_age }} </td>

                                    <td> {{ $update->name_vaccine }} </td>

                                    <td> {{ $update->illness_against }} </td>

                                    <td> {{ $update->status ? 'Valide' : 'Invalide' }} </td>
                                </tr>
                            @empty
                                <p class="text-danger text-center"> Aucune ligne trouvée</p>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            @endif
        </div>
    </div>
@endsection

resources/views/pages/search.blade.php
@extends('layouts.app', ['title' => 'Votre eCarnet'])

@section('main_content')
    <div class="row">
        <div class="col-md-6 mt-3 offset-md-3 mb-2">
            <h2 class="text-center"> {{ __('Voir votre eCarnet') }}</h2>

            @include('layouts.partials.flash_msg')

            <form action="{{ route('response') }}" method="post">
                @csrf

                <div class="form-group">
                    <label class="control-label" for="code_patient"> {{ __('Code patient') }} </label>
                    <input type="text" class="form-control" name="code_patient" id="code_patient" placeholder="Code patient">
                </div>

                <div class="form-group">
                    <label class="control-label" for="full_name"> {{ __('Nom complet') }} </label>
                    <input type="text" class="form-control" name="full_name" id="full_name" placeholder="Nom complet">
                </div>

                <div class="form-group">
                    <label class="control-label" for="birthday"> {{ __('Date de naissance') }} </label>
                    <input type="date" class="form-control" name="birthday" id="birthday"/>
                </div>

                <div class="form-group">
                    <label class="control-label" for="born_location"> {{ __('Lieu de naissance') }} </label>
                    <input type="text" class="form-control" name="born_location" id="born_location" placeholder="Lieu de naissance">
                </div>

                <div class="form-group">
                    <label class="control-label" for="name_father"> {{ __('Nom du père') }} </label>
                    <input type="text" class="form-control" name="name_father" id="name_father" placeholder="Nom du père">
                </div>

                <div class="form-group">
                    <label class="control-label" for="name_mother"> {{ __('Nom de la mère') }} </label>
                    <input type="text" class="form-control" name="name_mother" id="name_mother" placeholder="Nom de la mère">
                </div>

                <div class="mt-2 align-center offset-md-4">
                    <button class="btn btn-danger" onclick="javascript:history.back();">
                        {{ __('Annuler') }}
                    </button>

                    <button type="submit" id="submit_add_patient" class="btn btn-primary">
                        {{ __('Afficher') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script_js')
    <script>
        document.getElementById('region_id').removeAttribute('required')
    </script>
@endsection